"""add registrert_i_foretaksregisteret to company

Revision ID: 1b8a1659d72f
Revises: c3d4e5f6g7h8
Create Date: 2026-01-13 09:56:45.074633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1b8a1659d72f"
down_revision: Union[str, Sequence[str], None] = "c3d4e5f6g7h8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bedrifter",
        sa.Column("registrert_i_foretaksregisteret", sa.Boolean(), nullable=True, server_default=sa.text("false")),
    )
    op.create_index(
        op.f("ix_bedrifter_registrert_i_foretaksregisteret"),
        "bedrifter",
        ["registrert_i_foretaksregisteret"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bedrifter_registrert_i_foretaksregisteret"), table_name="bedrifter")
    op.drop_column("bedrifter", "registrert_i_foretaksregisteret")
    # ### end Alembic commands ###
