"""add_performance_indexes

Revision ID: 1d8fed3a8420
Revises: 9ad5a26519a9
Create Date: 2026-01-20 18:11:09.952284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d8fed3a8420"
down_revision: Union[str, Sequence[str], None] = "9ad5a26519a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bedrifter", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=True)
    op.create_index(
        "ix_bedrifter_fylkesnummer",
        "bedrifter",
        [sa.literal_column("left(forretningsadresse ->> 'kommunenummer', 2)")],
        unique=False,
    )
    op.create_index("ix_roller_foedselsdato", "roller", ["foedselsdato"], unique=False)
    op.create_index("ix_roller_person_navn_foedselsdato", "roller", ["person_navn", "foedselsdato"], unique=False)
    op.create_index(
        "ix_roller_person_navn_trgm",
        "roller",
        ["person_navn"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"person_navn": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_roller_person_navn_trgm",
        table_name="roller",
        postgresql_using="gin",
        postgresql_ops={"person_navn": "gin_trgm_ops"},
    )
    op.drop_index("ix_roller_person_navn_foedselsdato", table_name="roller")
    op.drop_index("ix_roller_foedselsdato", table_name="roller")
    op.drop_index("ix_bedrifter_fylkesnummer", table_name="bedrifter")
    op.alter_column("bedrifter", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=False)
    # ### end Alembic commands ###
