"""proven_schema_parity

Revision ID: 20d47b99003d
Revises: p4q5r6s7t8u9
Create Date: 2026-01-05 12:13:32.504670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20d47b99003d'
down_revision: Union[str, Sequence[str], None] = 'p4q5r6s7t8u9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bedrifter', 'geocoding_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bedrifter', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('bedrifter_search_vector_idx'), table_name='bedrifter', postgresql_using='gin')
    op.drop_index(op.f('idx_bedrifter_active_orgform'), table_name='bedrifter', postgresql_where='((konkurs IS NOT TRUE) AND (under_avvikling IS NOT TRUE) AND (under_tvangsavvikling IS NOT TRUE))')
    op.drop_index(op.f('idx_bedrifter_antall_ansatte'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_created_at'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_data'), table_name='bedrifter', postgresql_using='gin')
    op.drop_index(op.f('idx_bedrifter_kommune'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_konkurs'), table_name='bedrifter', postgresql_where='(konkurs = true)')
    op.drop_index(op.f('idx_bedrifter_konkursdato'), table_name='bedrifter', postgresql_where='(konkursdato IS NOT NULL)')
    op.drop_index(op.f('idx_bedrifter_last_polled_regnskap'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_list_covering'), table_name='bedrifter', postgresql_include=['orgnr', 'organisasjonsform', 'naeringskode', 'antall_ansatte', 'stiftelsesdato'])
    op.drop_index(op.f('idx_bedrifter_nace_ansatte'), table_name='bedrifter', postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.drop_index(op.f('idx_bedrifter_nace_founded'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_nace_kommune'), table_name='bedrifter', postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.drop_index(op.f('idx_bedrifter_naeringskode'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_naeringskode_pattern'), table_name='bedrifter', postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.drop_index(op.f('idx_bedrifter_naeringskode_prefix'), table_name='bedrifter', postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.drop_index(op.f('idx_bedrifter_navn'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_organisasjonsform'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_organisasjonsform_desc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_ansatte_desc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_json'), table_name='bedrifter', postgresql_where='(organisasjonsform IS NULL)')
    op.drop_index(op.f('idx_bedrifter_orgform_nace'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_navn_asc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_navn_desc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_orgnr_asc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_orgnr_desc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgform_stiftelse_desc'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_orgnr_pattern'), table_name='bedrifter', postgresql_ops={'orgnr': 'text_pattern_ops'})
    op.drop_index(op.f('idx_bedrifter_raw_data'), table_name='bedrifter', postgresql_using='gin')
    op.drop_index(op.f('idx_bedrifter_stiftelsesdato'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_under_avvikling'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_under_tvangsavvikling'), table_name='bedrifter')
    op.drop_index(op.f('idx_bedrifter_updated_at'), table_name='bedrifter')
    op.drop_index(op.f('idx_companies_geocoding_queue'), table_name='bedrifter', postgresql_where='(latitude IS NULL)')
    op.drop_index(op.f('idx_list_orgform_ansatte'), table_name='bedrifter', postgresql_where='((konkurs IS NOT TRUE) AND (under_avvikling IS NOT TRUE) AND (under_tvangsavvikling IS NOT TRUE))')
    op.drop_index(op.f('idx_similar_optimal'), table_name='bedrifter', postgresql_where='((konkurs = false) AND (under_avvikling = false) AND (under_tvangsavvikling = false))')
    op.drop_index(op.f('idx_similar_postnummer'), table_name='bedrifter', postgresql_where='((konkurs = false) AND (under_avvikling = false) AND (under_tvangsavvikling = false))')
    op.create_index('ix_bedrifter_kommunenummer', 'bedrifter', [sa.literal_column("left(forretningsadresse ->> 'kommunenummer', 4)")], unique=False)
    op.create_index(op.f('ix_bedrifter_naeringskode'), 'bedrifter', ['naeringskode'], unique=False)
    op.create_index(op.f('ix_bedrifter_navn'), 'bedrifter', ['navn'], unique=False)
    op.create_index(op.f('ix_bedrifter_orgnr'), 'bedrifter', ['orgnr'], unique=False)
    op.create_index('ix_bedrifter_search_vector', 'bedrifter', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('bedrifter', 'updated_at')
    op.drop_column('bedrifter', 'raw_data')
    op.drop_column('bedrifter', 'last_polled_regnskap')
    op.drop_column('bedrifter', 'maalform')
    op.drop_column('bedrifter', 'vedtektsdato')
    op.drop_index(op.f('idx_municipality_population_year_code'), table_name='municipality_population')
    op.add_column('regnskap', sa.Column('annen_driftsinntekt', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('varekostnad', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('lonnskostnad', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('nedskrivning', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('annen_driftskostnad', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('finansinntekt', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('finanskostnad', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('ordinaert_resultat_for_skatt', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('skattekostnad', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('sum_eiendeler', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('gjeld', sa.Float(), nullable=True))
    op.add_column('regnskap', sa.Column('sum_egenkapital_gjeld', sa.Float(), nullable=True))
    op.alter_column('regnskap', 'ebitda',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Generated: EBITDA = driftsresultat + avskrivninger',
               existing_nullable=True)
    op.alter_column('regnskap', 'ebitda_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Generated: EBITDA Margin = EBITDA / salgsinntekter',
               existing_nullable=True)
    op.alter_column('regnskap', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regnskap', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regnskap', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSONB storage for complete raw financial statement data from Regnskapsregisteret',
               existing_nullable=True)
    op.alter_column('regnskap', 'likviditetsgrad1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Generated: Liquidity Ratio 1 = omloepsmidler / kortsiktig_gjeld',
               existing_nullable=True)
    op.alter_column('regnskap', 'egenkapitalandel',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Generated: Equity Ratio = egenkapital / total assets',
               existing_nullable=True)
    op.drop_index(op.f('idx_regnskap_aar'), table_name='regnskap')
    op.drop_index(op.f('idx_regnskap_aarsresultat'), table_name='regnskap')
    op.drop_index(op.f('idx_regnskap_driftsresultat'), table_name='regnskap')
    op.drop_index(op.f('idx_regnskap_ebitda_margin'), table_name='regnskap', postgresql_where='(ebitda_margin IS NOT NULL)')
    op.drop_index(op.f('idx_regnskap_egenkapital'), table_name='regnskap')
    op.drop_index(op.f('idx_regnskap_egenkapitalandel'), table_name='regnskap', postgresql_where='(egenkapitalandel IS NOT NULL)')
    op.drop_index(op.f('idx_regnskap_likviditetsgrad1'), table_name='regnskap', postgresql_where='(likviditetsgrad1 IS NOT NULL)')
    op.drop_index(op.f('idx_regnskap_raw_data'), table_name='regnskap', postgresql_using='gin')
    op.drop_index(op.f('idx_regnskap_salgsinntekter'), table_name='regnskap')
    op.drop_index(op.f('ix_regnskap_periode_til'), table_name='regnskap')
    op.drop_constraint(op.f('uq_regnskap_orgnr_aar'), 'regnskap', type_='unique')
    op.create_index(op.f('ix_regnskap_aar'), 'regnskap', ['aar'], unique=False)
    op.drop_constraint(op.f('fk_regnskap_orgnr'), 'regnskap', type_='foreignkey')
    op.create_foreign_key(None, 'regnskap', 'bedrifter', ['orgnr'], ['orgnr'])
    op.create_index(op.f('ix_roller_id'), 'roller', ['id'], unique=False)
    op.drop_constraint(op.f('roller_orgnr_fkey'), 'roller', type_='foreignkey')
    op.create_foreign_key(None, 'roller', 'bedrifter', ['orgnr'], ['orgnr'])
    op.alter_column('underenheter', 'parent_orgnr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('underenheter', 'navn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_underenheter_navn_test'), table_name='underenheter')
    op.drop_constraint(op.f('underenheter_parent_orgnr_fkey'), 'underenheter', type_='foreignkey')
    op.create_foreign_key(None, 'underenheter', 'bedrifter', ['parent_orgnr'], ['orgnr'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'underenheter', type_='foreignkey')
    op.create_foreign_key(op.f('underenheter_parent_orgnr_fkey'), 'underenheter', 'bedrifter', ['parent_orgnr'], ['orgnr'], ondelete='CASCADE')
    op.create_index(op.f('ix_underenheter_navn_test'), 'underenheter', ['navn'], unique=False)
    op.alter_column('underenheter', 'navn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('underenheter', 'parent_orgnr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'roller', type_='foreignkey')
    op.create_foreign_key(op.f('roller_orgnr_fkey'), 'roller', 'bedrifter', ['orgnr'], ['orgnr'], ondelete='CASCADE')
    op.drop_index(op.f('ix_roller_id'), table_name='roller')
    op.drop_constraint(None, 'regnskap', type_='foreignkey')
    op.create_foreign_key(op.f('fk_regnskap_orgnr'), 'regnskap', 'bedrifter', ['orgnr'], ['orgnr'], ondelete='CASCADE')
    op.drop_index(op.f('ix_regnskap_aar'), table_name='regnskap')
    op.create_unique_constraint(op.f('uq_regnskap_orgnr_aar'), 'regnskap', ['orgnr', 'aar'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_regnskap_periode_til'), 'regnskap', ['periode_til'], unique=False)
    op.create_index(op.f('idx_regnskap_salgsinntekter'), 'regnskap', ['salgsinntekter'], unique=False)
    op.create_index(op.f('idx_regnskap_raw_data'), 'regnskap', ['raw_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_regnskap_likviditetsgrad1'), 'regnskap', ['likviditetsgrad1'], unique=False, postgresql_where='(likviditetsgrad1 IS NOT NULL)')
    op.create_index(op.f('idx_regnskap_egenkapitalandel'), 'regnskap', ['egenkapitalandel'], unique=False, postgresql_where='(egenkapitalandel IS NOT NULL)')
    op.create_index(op.f('idx_regnskap_egenkapital'), 'regnskap', ['egenkapital'], unique=False)
    op.create_index(op.f('idx_regnskap_ebitda_margin'), 'regnskap', ['ebitda_margin'], unique=False, postgresql_where='(ebitda_margin IS NOT NULL)')
    op.create_index(op.f('idx_regnskap_driftsresultat'), 'regnskap', ['driftsresultat'], unique=False)
    op.create_index(op.f('idx_regnskap_aarsresultat'), 'regnskap', ['aarsresultat'], unique=False)
    op.create_index(op.f('idx_regnskap_aar'), 'regnskap', ['aar'], unique=False)
    op.alter_column('regnskap', 'egenkapitalandel',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Generated: Equity Ratio = egenkapital / total assets',
               existing_nullable=True)
    op.alter_column('regnskap', 'likviditetsgrad1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Generated: Liquidity Ratio = omloepsmidler / kortsiktig_gjeld',
               existing_nullable=True)
    op.alter_column('regnskap', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSONB storage for complete raw financial statement data from Regnskapsregisteret',
               existing_nullable=True)
    op.alter_column('regnskap', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regnskap', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regnskap', 'ebitda_margin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Generated: EBITDA Margin = EBITDA / salgsinntekter',
               existing_nullable=True)
    op.alter_column('regnskap', 'ebitda',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Generated: EBITDA = driftsresultat + avskrivninger',
               existing_nullable=True)
    op.drop_column('regnskap', 'sum_egenkapital_gjeld')
    op.drop_column('regnskap', 'gjeld')
    op.drop_column('regnskap', 'sum_eiendeler')
    op.drop_column('regnskap', 'skattekostnad')
    op.drop_column('regnskap', 'ordinaert_resultat_for_skatt')
    op.drop_column('regnskap', 'finanskostnad')
    op.drop_column('regnskap', 'finansinntekt')
    op.drop_column('regnskap', 'annen_driftskostnad')
    op.drop_column('regnskap', 'nedskrivning')
    op.drop_column('regnskap', 'lonnskostnad')
    op.drop_column('regnskap', 'varekostnad')
    op.drop_column('regnskap', 'annen_driftsinntekt')
    op.create_index(op.f('idx_municipality_population_year_code'), 'municipality_population', ['year', 'municipality_code'], unique=False)
    op.add_column('bedrifter', sa.Column('vedtektsdato', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bedrifter', sa.Column('maalform', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('bedrifter', sa.Column('last_polled_regnskap', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bedrifter', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSONB storage for complete raw company data from Enhetsregisteret'))
    op.add_column('bedrifter', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index('ix_bedrifter_search_vector', table_name='bedrifter', postgresql_using='gin')
    op.drop_index(op.f('ix_bedrifter_orgnr'), table_name='bedrifter')
    op.drop_index(op.f('ix_bedrifter_navn'), table_name='bedrifter')
    op.drop_index(op.f('ix_bedrifter_naeringskode'), table_name='bedrifter')
    op.drop_index('ix_bedrifter_kommunenummer', table_name='bedrifter')
    op.create_index(op.f('idx_similar_postnummer'), 'bedrifter', ['naeringskode', sa.literal_column("(forretningsadresse ->> 'postnummer'::text)"), sa.literal_column('antall_ansatte DESC NULLS LAST')], unique=False, postgresql_where='((konkurs = false) AND (under_avvikling = false) AND (under_tvangsavvikling = false))')
    op.create_index(op.f('idx_similar_optimal'), 'bedrifter', [sa.literal_column('"left"(naeringskode::text, 3)'), sa.literal_column("upper(forretningsadresse ->> 'kommune'::text)"), sa.literal_column('antall_ansatte DESC NULLS LAST')], unique=False, postgresql_where='((konkurs = false) AND (under_avvikling = false) AND (under_tvangsavvikling = false))')
    op.create_index(op.f('idx_list_orgform_ansatte'), 'bedrifter', ['organisasjonsform', sa.literal_column('antall_ansatte DESC')], unique=False, postgresql_where='((konkurs IS NOT TRUE) AND (under_avvikling IS NOT TRUE) AND (under_tvangsavvikling IS NOT TRUE))')
    op.create_index(op.f('idx_companies_geocoding_queue'), 'bedrifter', [sa.literal_column('antall_ansatte DESC NULLS LAST')], unique=False, postgresql_where='(latitude IS NULL)')
    op.create_index(op.f('idx_bedrifter_updated_at'), 'bedrifter', ['updated_at'], unique=False)
    op.create_index(op.f('idx_bedrifter_under_tvangsavvikling'), 'bedrifter', ['under_tvangsavvikling'], unique=False)
    op.create_index(op.f('idx_bedrifter_under_avvikling'), 'bedrifter', ['under_avvikling'], unique=False)
    op.create_index(op.f('idx_bedrifter_stiftelsesdato'), 'bedrifter', ['stiftelsesdato'], unique=False)
    op.create_index(op.f('idx_bedrifter_raw_data'), 'bedrifter', ['raw_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_bedrifter_orgnr_pattern'), 'bedrifter', ['orgnr'], unique=False, postgresql_ops={'orgnr': 'text_pattern_ops'})
    op.create_index(op.f('idx_bedrifter_orgform_stiftelse_desc'), 'bedrifter', ['organisasjonsform', sa.literal_column('stiftelsesdato DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_orgnr_desc'), 'bedrifter', ['organisasjonsform', sa.literal_column('orgnr DESC')], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_orgnr_asc'), 'bedrifter', ['organisasjonsform', 'orgnr'], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_navn_desc'), 'bedrifter', ['organisasjonsform', sa.literal_column('navn DESC')], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_navn_asc'), 'bedrifter', ['organisasjonsform', 'navn'], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_nace'), 'bedrifter', ['organisasjonsform', 'naeringskode'], unique=False)
    op.create_index(op.f('idx_bedrifter_orgform_json'), 'bedrifter', [sa.literal_column("((data -> 'organisasjonsform'::text) ->> 'kode'::text)")], unique=False, postgresql_where='(organisasjonsform IS NULL)')
    op.create_index(op.f('idx_bedrifter_orgform_ansatte_desc'), 'bedrifter', ['organisasjonsform', sa.literal_column('antall_ansatte DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_bedrifter_organisasjonsform_desc'), 'bedrifter', [sa.literal_column('organisasjonsform DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_bedrifter_organisasjonsform'), 'bedrifter', ['organisasjonsform'], unique=False)
    op.create_index(op.f('idx_bedrifter_navn'), 'bedrifter', ['navn'], unique=False)
    op.create_index(op.f('idx_bedrifter_naeringskode_prefix'), 'bedrifter', ['naeringskode'], unique=False, postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.create_index(op.f('idx_bedrifter_naeringskode_pattern'), 'bedrifter', ['naeringskode'], unique=False, postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.create_index(op.f('idx_bedrifter_naeringskode'), 'bedrifter', ['naeringskode'], unique=False)
    op.create_index(op.f('idx_bedrifter_nace_kommune'), 'bedrifter', ['naeringskode', sa.literal_column("(forretningsadresse ->> 'kommune'::text)")], unique=False, postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.create_index(op.f('idx_bedrifter_nace_founded'), 'bedrifter', ['naeringskode', sa.literal_column('stiftelsesdato DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_bedrifter_nace_ansatte'), 'bedrifter', ['naeringskode', sa.literal_column('antall_ansatte DESC NULLS LAST')], unique=False, postgresql_ops={'naeringskode': 'text_pattern_ops'})
    op.create_index(op.f('idx_bedrifter_list_covering'), 'bedrifter', ['navn'], unique=False, postgresql_include=['orgnr', 'organisasjonsform', 'naeringskode', 'antall_ansatte', 'stiftelsesdato'])
    op.create_index(op.f('idx_bedrifter_last_polled_regnskap'), 'bedrifter', ['last_polled_regnskap'], unique=False)
    op.create_index(op.f('idx_bedrifter_konkursdato'), 'bedrifter', [sa.literal_column('konkursdato DESC NULLS LAST')], unique=False, postgresql_where='(konkursdato IS NOT NULL)')
    op.create_index(op.f('idx_bedrifter_konkurs'), 'bedrifter', ['konkurs'], unique=False, postgresql_where='(konkurs = true)')
    op.create_index(op.f('idx_bedrifter_kommune'), 'bedrifter', [sa.literal_column("(forretningsadresse ->> 'kommune'::text)")], unique=False)
    op.create_index(op.f('idx_bedrifter_data'), 'bedrifter', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_bedrifter_created_at'), 'bedrifter', ['created_at'], unique=False)
    op.create_index(op.f('idx_bedrifter_antall_ansatte'), 'bedrifter', ['antall_ansatte'], unique=False)
    op.create_index(op.f('idx_bedrifter_active_orgform'), 'bedrifter', ['organisasjonsform'], unique=False, postgresql_where='((konkurs IS NOT TRUE) AND (under_avvikling IS NOT TRUE) AND (under_tvangsavvikling IS NOT TRUE))')
    op.create_index(op.f('bedrifter_search_vector_idx'), 'bedrifter', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('bedrifter', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bedrifter', 'geocoding_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
