"""add registration dates to companies

Revision ID: 3ad69e2d8e85
Revises: d9c85dd327d1
Create Date: 2026-01-20 08:17:04.275719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ad69e2d8e85"
down_revision: Union[str, Sequence[str], None] = "d9c85dd327d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bedrifter", sa.Column("registreringsdato_enhetsregisteret", sa.Date(), nullable=True))
    op.add_column("bedrifter", sa.Column("registreringsdato_foretaksregisteret", sa.Date(), nullable=True))
    op.alter_column("bedrifter", "konkurs", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("bedrifter", "under_avvikling", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("bedrifter", "under_tvangsavvikling", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "bedrifter",
        "registrert_i_foretaksregisteret",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "bedrifter",
        "geocoding_attempts",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("bedrifter", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=False)
    op.alter_column(
        "bedrifter",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_bedrifter_registreringsdato_enhetsregisteret"),
        "bedrifter",
        ["registreringsdato_enhetsregisteret"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bedrifter_registreringsdato_foretaksregisteret"),
        "bedrifter",
        ["registreringsdato_foretaksregisteret"],
        unique=False,
    )
    op.alter_column(
        "bulk_import_queue",
        "status",
        existing_type=postgresql.ENUM("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", "SKIPPED", name="importstatus"),
        nullable=False,
    )
    op.alter_column("bulk_import_queue", "priority", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bulk_import_queue", "queued_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("bulk_import_queue", "attempt_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bulk_import_queue", "company_fetched", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bulk_import_queue", "financials_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("import_batches", "batch_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("import_batches", "started_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("import_batches", "total_companies", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("import_batches", "completed_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("import_batches", "failed_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("import_batches", "skipped_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("import_batches", "companies_per_hour", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "municipality_population",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("regnskap", "orgnr", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("regnskap", "aar", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "regnskap",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "regnskap",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roller", "fratraadt", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "roller",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roller",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("underenheter", "parent_orgnr", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("underenheter", "navn", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("underenheter", "antall_ansatte", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "underenheter",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "underenheter",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("underenheter", "antall_ansatte", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("underenheter", "navn", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("underenheter", "parent_orgnr", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "roller",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roller",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roller", "fratraadt", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "regnskap",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "regnskap",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("regnskap", "aar", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("regnskap", "orgnr", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "municipality_population",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("import_batches", "companies_per_hour", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("import_batches", "skipped_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("import_batches", "failed_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("import_batches", "completed_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("import_batches", "total_companies", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("import_batches", "started_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("import_batches", "batch_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("bulk_import_queue", "financials_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bulk_import_queue", "company_fetched", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bulk_import_queue", "attempt_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bulk_import_queue", "queued_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("bulk_import_queue", "priority", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "bulk_import_queue",
        "status",
        existing_type=postgresql.ENUM("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", "SKIPPED", name="importstatus"),
        nullable=True,
    )
    op.drop_index(op.f("ix_bedrifter_registreringsdato_foretaksregisteret"), table_name="bedrifter")
    op.drop_index(op.f("ix_bedrifter_registreringsdato_enhetsregisteret"), table_name="bedrifter")
    op.alter_column(
        "bedrifter",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("bedrifter", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=True)
    op.alter_column(
        "bedrifter",
        "geocoding_attempts",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "bedrifter",
        "registrert_i_foretaksregisteret",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("bedrifter", "under_tvangsavvikling", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("bedrifter", "under_avvikling", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("bedrifter", "konkurs", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("bedrifter", "registreringsdato_foretaksregisteret")
    op.drop_column("bedrifter", "registreringsdato_enhetsregisteret")
    # ### end Alembic commands ###
