"""Add registration date and data to subunits

Revision ID: 3b23c18900f4
Revises: 09bf64606e67
Create Date: 2026-01-26 08:31:04.419409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b23c18900f4"
down_revision: Union[str, Sequence[str], None] = "09bf64606e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("underenheter", sa.Column("registreringsdato_enhetsregisteret", sa.Date(), nullable=True))
    op.add_column("underenheter", sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(
        op.f("ix_underenheter_registreringsdato_enhetsregisteret"),
        "underenheter",
        ["registreringsdato_enhetsregisteret"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_underenheter_registreringsdato_enhetsregisteret"), table_name="underenheter")
    op.drop_column("underenheter", "data")
    op.drop_column("underenheter", "registreringsdato_enhetsregisteret")
    # ### end Alembic commands ###
