"""add_municipality_performance_optimizations

Revision ID: 7a496d410589
Revises: 3b23c18900f4
Create Date: 2026-01-26 09:03:15.847933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a496d410589"
down_revision: Union[str, Sequence[str], None] = "3b23c18900f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add name column to municipality_population
    op.add_column("municipality_population", sa.Column("name", sa.String(), nullable=True))

    # 2. Backfill names from bedrock database (one-time migration cost)
    op.execute("""
        UPDATE municipality_population mp 
        SET name = INITCAP(b.name) 
        FROM (
            SELECT DISTINCT (forretningsadresse->>'kommunenummer') as code, (forretningsadresse->>'kommune') as name 
            FROM bedrifter 
            WHERE (forretningsadresse->>'kommunenummer') IS NOT NULL
        ) b 
        WHERE mp.municipality_code = b.code AND mp.name IS NULL;
    """)

    # 3. Create high-performance composite indexes for municipality-scoped dashboards
    # Note: Using manual SQL for complex functional indexes to ensure exact parity with database engine expectations
    op.execute("""
        CREATE INDEX idx_bedrifter_muni_stiftelse 
        ON bedrifter ((forretningsadresse ->> 'kommunenummer'), stiftelsesdato DESC NULLS LAST);
    """)
    op.execute("""
        CREATE INDEX idx_bedrifter_muni_ansatte 
        ON bedrifter ((forretningsadresse ->> 'kommunenummer'), antall_ansatte DESC NULLS LAST);
    """)
    op.execute("""
        CREATE INDEX idx_bedrifter_muni_konkurs_partial 
        ON bedrifter ((forretningsadresse ->> 'kommunenummer'), konkursdato DESC NULLS LAST)
        WHERE konkurs IS TRUE;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("municipality_population", "name")
    op.drop_index("idx_bedrifter_muni_stiftelse", table_name="bedrifter")
    op.drop_index(
        "idx_bedrifter_muni_konkurs_partial", table_name="bedrifter", postgresql_where=sa.text("konkurs IS TRUE")
    )
    op.drop_index("idx_bedrifter_muni_ansatte", table_name="bedrifter")
    # ### end Alembic commands ###
