"""add expanded register flags

Revision ID: 9ad5a26519a9
Revises: 3ad69e2d8e85
Create Date: 2026-01-20 08:28:18.143796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ad5a26519a9"
down_revision: Union[str, Sequence[str], None] = "3ad69e2d8e85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bedrifter",
        sa.Column("registrert_i_mvaregisteret", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "bedrifter",
        sa.Column(
            "registrert_i_frivillighetsregisteret", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "bedrifter",
        sa.Column("registrert_i_stiftelsesregisteret", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "bedrifter",
        sa.Column("registrert_i_partiregisteret", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        "idx_bedrifter_reg_enhetsregisteret_desc",
        "bedrifter",
        [sa.text("registreringsdato_enhetsregisteret DESC NULLS LAST")],
        unique=False,
    )
    op.create_index(
        "idx_bedrifter_reg_foretaksregisteret_desc",
        "bedrifter",
        [sa.text("registreringsdato_foretaksregisteret DESC NULLS LAST")],
        unique=False,
    )
    op.create_index(
        op.f("ix_bedrifter_registrert_i_frivillighetsregisteret"),
        "bedrifter",
        ["registrert_i_frivillighetsregisteret"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bedrifter_registrert_i_mvaregisteret"), "bedrifter", ["registrert_i_mvaregisteret"], unique=False
    )
    op.create_index(
        op.f("ix_bedrifter_registrert_i_partiregisteret"), "bedrifter", ["registrert_i_partiregisteret"], unique=False
    )
    op.create_index(
        op.f("ix_bedrifter_registrert_i_stiftelsesregisteret"),
        "bedrifter",
        ["registrert_i_stiftelsesregisteret"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bedrifter_registrert_i_stiftelsesregisteret"), table_name="bedrifter")
    op.drop_index(op.f("ix_bedrifter_registrert_i_partiregisteret"), table_name="bedrifter")
    op.drop_index(op.f("ix_bedrifter_registrert_i_mvaregisteret"), table_name="bedrifter")
    op.drop_index(op.f("ix_bedrifter_registrert_i_frivillighetsregisteret"), table_name="bedrifter")
    op.drop_index("idx_bedrifter_reg_foretaksregisteret_desc", table_name="bedrifter")
    op.drop_index("idx_bedrifter_reg_enhetsregisteret_desc", table_name="bedrifter")
    op.drop_column("bedrifter", "registrert_i_partiregisteret")
    op.drop_column("bedrifter", "registrert_i_stiftelsesregisteret")
    op.drop_column("bedrifter", "registrert_i_frivillighetsregisteret")
    op.drop_column("bedrifter", "registrert_i_mvaregisteret")
    # ### end Alembic commands ###
