"""add_partial_index_for_financial_polling

Revision ID: a69b80bb0302
Revises: s7t8u9v0w1x2
Create Date: 2026-01-06 07:13:11.390040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a69b80bb0302"
down_revision: Union[str, Sequence[str], None] = "s7t8u9v0w1x2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Only create the new partial index for optimization
    op.create_index(
        "idx_bedrifter_needs_financial_polling",
        "bedrifter",
        ["orgnr"],
        unique=False,
        postgresql_where=sa.text("last_polled_regnskap IS NULL"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Only drop the new index on rollback
    op.drop_index(
        "idx_bedrifter_needs_financial_polling",
        table_name="bedrifter",
        postgresql_where=sa.text("last_polled_regnskap IS NULL"),
    )

    # ### end Alembic commands ###
