"""NACE division codes and names (Norwegian Standard Industrial Classification)"""

# NACE division names (top-level, 2-digit codes)
NACE_DIVISIONS: dict[str, str] = {
    "01": "Jordbruk og tjenester tilknyttet jordbruk, jakt og viltstell",
    "02": "Skogbruk og tjenester tilknyttet skogbruk",
    "03": "Fiske, fangst og akvakultur",
    "05": "Bryting av steinkull og brunkull",
    "06": "Utvinning av råolje og naturgass",
    "07": "Bryting av metallholdig malm",
    "08": "Bryting og bergverksdrift ellers",
    "09": "Tjenester tilknyttet bergverksdrift og utvinning",
    "10": "Produksjon av næringsmidler",
    "11": "Produksjon av drikkevarer",
    "12": "Produksjon av tobakksvarer",
    "13": "Produksjon av tekstiler",
    "14": "Produksjon av klær",
    "15": "Produksjon av lær og lærvarer",
    "16": "Produksjon av trelast og varer av tre, kork, strå og flettematerialer",
    "17": "Produksjon av papir og papirvarer",
    "18": "Trykking og reproduksjon av innspilte opptak",
    "19": "Produksjon av kull- og raffinerte petroleumsprodukter",
    "20": "Produksjon av kjemikalier og kjemiske produkter",
    "21": "Produksjon av farmasøytiske råvarer og preparater",
    "22": "Produksjon av gummi- og plastprodukter",
    "23": "Produksjon av andre ikke-metallholdige mineralprodukter",
    "24": "Produksjon av metaller",
    "25": "Produksjon av metallvarer, unntatt maskiner og utstyr",
    "26": "Produksjon av datamaskiner og elektroniske og optiske produkter",
    "27": "Produksjon av elektrisk utstyr",
    "28": "Produksjon av maskiner og utstyr til generell bruk",
    "29": "Produksjon av motorvogner og tilhengere",
    "30": "Produksjon av andre transportmidler",
    "31": "Produksjon av møbler",
    "32": "Annen industriproduksjon",
    "33": "Reparasjon og installasjon av maskiner og utstyr",
    "35": "Elektrisitets-, gass-, damp- og varmtvannsforsyning",
    "36": "Uttak fra kilde, rensing og distribusjon av vann",
    "37": "Oppsamling og behandling av avløpsvann",
    "38": "Innsamling, behandling, disponering og gjenvinning av avfall",
    "39": "Miljørydding, -rensing og lignende virksomhet",
    "41": "Oppføring av bygninger",
    "42": "Anleggsvirksomhet",
    "43": "Spesialisert bygge- og anleggsvirksomhet",
    "45": "Handel med og reparasjon av motorvogner",
    "46": "Agentur- og engroshandel, unntatt med motorvogner",
    "47": "Detaljhandel, unntatt med motorvogner",
    "49": "Landtransport og rørtransport",
    "50": "Sjøfart",
    "51": "Lufttransport",
    "52": "Lagring og andre tjenester tilknyttet transport",
    "53": "Post og distribusjonsvirksomhet",
    "55": "Overnattingsvirksomhet",
    "56": "Serveringsvirksomhet",
    "58": "Forlagsvirksomhet",
    "59": "Film-, video- og fjernsynsprogramproduksjon, utgivelse av musikk",
    "60": "Radio- og fjernsynskringkasting",
    "61": "Telekommunikasjon",
    "62": "Tjenester tilknyttet informasjonsteknologi",
    "63": "Informasjonstjenester",
    "64": "Finansieringsvirksomhet",
    "65": "Forsikringsvirksomhet og pensjonskasser",
    "66": "Tjenester tilknyttet finansierings- og forsikringsvirksomhet",
    "68": "Omsetning og drift av fast eiendom",
    "69": "Juridisk og regnskapsmessig tjenesteyting",
    "70": "Hovedkontortjenester, administrativ rådgivning",
    "71": "Arkitektvirksomhet og teknisk konsulentvirksomhet",
    "72": "Forskning og utviklingsarbeid",
    "73": "Annonse- og reklamevirksomhet og markedsundersøkelser",
    "74": "Annen faglig, vitenskapelig og teknisk virksomhet",
    "75": "Veterinærtjenester",
    "77": "Utleievirksomhet",
    "78": "Arbeidskrafttjenester",
    "79": "Reisebyrå- og reisearrangørvirksomhet",
    "80": "Vakttjeneste og etterforsking",
    "81": "Tjenester tilknyttet eiendomsdrift",
    "82": "Annen forretningsmessig tjenesteyting",
    "84": "Offentlig administrasjon og forsvar, trygdeordninger",
    "85": "Undervisning",
    "86": "Helsetjenester",
    "87": "Pleie- og omsorgstjenester i institusjon",
    "88": "Sosiale omsorgstjenester uten botilbud",
    "90": "Kunstnerisk virksomhet og underholdningsvirksomhet",
    "91": "Drift av biblioteker, arkiver, museer og annen kulturvirksomhet",
    "92": "Lotteri og totalisatorspill",
    "93": "Sports- og fritidsaktiviteter og drift av fornøyelsesetablissementer",
    "94": "Aktiviteter i medlemsorganisasjoner",
    "95": "Reparasjon av datamaskiner, husholdningsvarer og varer til personlig bruk",
    "96": "Annen personlig tjenesteyting",
    "97": "Lønnet arbeid i private husholdninger",
    "99": "Internasjonale organisasjoner og organer",
    "00": "Uspesifisert næring",
}


def get_nace_name(nace_code: str) -> str:
    """Get the Norwegian name for a NACE code.

    Handles both division codes (2 digits, e.g. '62') and
    subclass codes (5-6 chars, e.g. '62.010').
    For subclass codes, returns the division name.
    """
    # Extract division (first 2 digits) for subclass codes
    division = nace_code[:2] if len(nace_code) >= 2 else nace_code
    return NACE_DIVISIONS.get(division, f"Ukjent ({nace_code})")
