/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtforskRouteImport } from './routes/utforsk'
import { Route as SammenlignRouteImport } from './routes/sammenlign'
import { Route as OmRouteImport } from './routes/om'
import { Route as NyetableringerRouteImport } from './routes/nyetableringer'
import { Route as KonkurserRouteImport } from './routes/konkurser'
import { Route as KartRouteImport } from './routes/kart'
import { Route as BransjerRouteImport } from './routes/bransjer'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BedriftOrgnrRouteImport } from './routes/bedrift.$orgnr'
import { Route as PersonNameBirthdateRouteImport } from './routes/person.$name.$birthdate'

const UtforskRoute = UtforskRouteImport.update({
  id: '/utforsk',
  path: '/utforsk',
  getParentRoute: () => rootRouteImport,
} as any)
const SammenlignRoute = SammenlignRouteImport.update({
  id: '/sammenlign',
  path: '/sammenlign',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const NyetableringerRoute = NyetableringerRouteImport.update({
  id: '/nyetableringer',
  path: '/nyetableringer',
  getParentRoute: () => rootRouteImport,
} as any)
const KonkurserRoute = KonkurserRouteImport.update({
  id: '/konkurser',
  path: '/konkurser',
  getParentRoute: () => rootRouteImport,
} as any)
const KartRoute = KartRouteImport.update({
  id: '/kart',
  path: '/kart',
  getParentRoute: () => rootRouteImport,
} as any)
const BransjerRoute = BransjerRouteImport.update({
  id: '/bransjer',
  path: '/bransjer',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BedriftOrgnrRoute = BedriftOrgnrRouteImport.update({
  id: '/bedrift/$orgnr',
  path: '/bedrift/$orgnr',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/bedrift.$orgnr.lazy').then((d) => d.Route),
)
const PersonNameBirthdateRoute = PersonNameBirthdateRouteImport.update({
  id: '/person/$name/$birthdate',
  path: '/person/$name/$birthdate',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/person.$name.$birthdate.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bransjer': typeof BransjerRoute
  '/kart': typeof KartRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bransjer': typeof BransjerRoute
  '/kart': typeof KartRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bransjer': typeof BransjerRoute
  '/kart': typeof KartRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/bransjer'
    | '/kart'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/sammenlign'
    | '/utforsk'
    | '/bedrift/$orgnr'
    | '/person/$name/$birthdate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bransjer'
    | '/kart'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/sammenlign'
    | '/utforsk'
    | '/bedrift/$orgnr'
    | '/person/$name/$birthdate'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/bransjer'
    | '/kart'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/sammenlign'
    | '/utforsk'
    | '/bedrift/$orgnr'
    | '/person/$name/$birthdate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BransjerRoute: typeof BransjerRoute
  KartRoute: typeof KartRoute
  KonkurserRoute: typeof KonkurserRoute
  NyetableringerRoute: typeof NyetableringerRoute
  OmRoute: typeof OmRoute
  SammenlignRoute: typeof SammenlignRoute
  UtforskRoute: typeof UtforskRoute
  BedriftOrgnrRoute: typeof BedriftOrgnrRoute
  PersonNameBirthdateRoute: typeof PersonNameBirthdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utforsk': {
      id: '/utforsk'
      path: '/utforsk'
      fullPath: '/utforsk'
      preLoaderRoute: typeof UtforskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sammenlign': {
      id: '/sammenlign'
      path: '/sammenlign'
      fullPath: '/sammenlign'
      preLoaderRoute: typeof SammenlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyetableringer': {
      id: '/nyetableringer'
      path: '/nyetableringer'
      fullPath: '/nyetableringer'
      preLoaderRoute: typeof NyetableringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konkurser': {
      id: '/konkurser'
      path: '/konkurser'
      fullPath: '/konkurser'
      preLoaderRoute: typeof KonkurserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kart': {
      id: '/kart'
      path: '/kart'
      fullPath: '/kart'
      preLoaderRoute: typeof KartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bransjer': {
      id: '/bransjer'
      path: '/bransjer'
      fullPath: '/bransjer'
      preLoaderRoute: typeof BransjerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrift/$orgnr': {
      id: '/bedrift/$orgnr'
      path: '/bedrift/$orgnr'
      fullPath: '/bedrift/$orgnr'
      preLoaderRoute: typeof BedriftOrgnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$name/$birthdate': {
      id: '/person/$name/$birthdate'
      path: '/person/$name/$birthdate'
      fullPath: '/person/$name/$birthdate'
      preLoaderRoute: typeof PersonNameBirthdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BransjerRoute: BransjerRoute,
  KartRoute: KartRoute,
  KonkurserRoute: KonkurserRoute,
  NyetableringerRoute: NyetableringerRoute,
  OmRoute: OmRoute,
  SammenlignRoute: SammenlignRoute,
  UtforskRoute: UtforskRoute,
  BedriftOrgnrRoute: BedriftOrgnrRoute,
  PersonNameBirthdateRoute: PersonNameBirthdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
