/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as UtforskRouteImport } from './routes/utforsk'
import { Route as SammenlignRouteImport } from './routes/sammenlign'
import { Route as RegionerRouteImport } from './routes/regioner'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as PersonerRouteImport } from './routes/personer'
import { Route as PersonRouteImport } from './routes/person'
import { Route as OppdateringerRouteImport } from './routes/oppdateringer'
import { Route as OmRouteImport } from './routes/om'
import { Route as NyetableringerRouteImport } from './routes/nyetableringer'
import { Route as KonkurserRouteImport } from './routes/konkurser'
import { Route as KommunerRouteImport } from './routes/kommuner'
import { Route as KartRouteImport } from './routes/kart'
import { Route as FylkerRouteImport } from './routes/fylker'
import { Route as DatakilderRouteImport } from './routes/datakilder'
import { Route as BransjerRouteImport } from './routes/bransjer'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonIndexRouteImport } from './routes/person.index'
import { Route as VirksomhetOrgnrRouteImport } from './routes/virksomhet.$orgnr'
import { Route as KommuneCodeRouteImport } from './routes/kommune.$code'
import { Route as FylkeCodeRouteImport } from './routes/fylke.$code'
import { Route as BransjeCodeRouteImport } from './routes/bransje.$code'
import { Route as BedriftOrgnrRouteImport } from './routes/bedrift.$orgnr'
import { Route as PersonNameBirthdateRouteImport } from './routes/person.$name.$birthdate'

const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const UtforskRoute = UtforskRouteImport.update({
  id: '/utforsk',
  path: '/utforsk',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/utforsk.lazy').then((d) => d.Route))
const SammenlignRoute = SammenlignRouteImport.update({
  id: '/sammenlign',
  path: '/sammenlign',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sammenlign.lazy').then((d) => d.Route))
const RegionerRoute = RegionerRouteImport.update({
  id: '/regioner',
  path: '/regioner',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/regioner.lazy').then((d) => d.Route))
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonerRoute = PersonerRouteImport.update({
  id: '/personer',
  path: '/personer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/personer.lazy').then((d) => d.Route))
const PersonRoute = PersonRouteImport.update({
  id: '/person',
  path: '/person',
  getParentRoute: () => rootRouteImport,
} as any)
const OppdateringerRoute = OppdateringerRouteImport.update({
  id: '/oppdateringer',
  path: '/oppdateringer',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/om.lazy').then((d) => d.Route))
const NyetableringerRoute = NyetableringerRouteImport.update({
  id: '/nyetableringer',
  path: '/nyetableringer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/nyetableringer.lazy').then((d) => d.Route),
)
const KonkurserRoute = KonkurserRouteImport.update({
  id: '/konkurser',
  path: '/konkurser',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/konkurser.lazy').then((d) => d.Route))
const KommunerRoute = KommunerRouteImport.update({
  id: '/kommuner',
  path: '/kommuner',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kommuner.lazy').then((d) => d.Route))
const KartRoute = KartRouteImport.update({
  id: '/kart',
  path: '/kart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kart.lazy').then((d) => d.Route))
const FylkerRoute = FylkerRouteImport.update({
  id: '/fylker',
  path: '/fylker',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fylker.lazy').then((d) => d.Route))
const DatakilderRoute = DatakilderRouteImport.update({
  id: '/datakilder',
  path: '/datakilder',
  getParentRoute: () => rootRouteImport,
} as any)
const BransjerRoute = BransjerRouteImport.update({
  id: '/bransjer',
  path: '/bransjer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bransjer.lazy').then((d) => d.Route))
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PersonIndexRoute = PersonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonRoute,
} as any).lazy(() => import('./routes/person.index.lazy').then((d) => d.Route))
const VirksomhetOrgnrRoute = VirksomhetOrgnrRouteImport.update({
  id: '/virksomhet/$orgnr',
  path: '/virksomhet/$orgnr',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/virksomhet.$orgnr.lazy').then((d) => d.Route),
)
const KommuneCodeRoute = KommuneCodeRouteImport.update({
  id: '/kommune/$code',
  path: '/kommune/$code',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kommune.$code.lazy').then((d) => d.Route))
const FylkeCodeRoute = FylkeCodeRouteImport.update({
  id: '/fylke/$code',
  path: '/fylke/$code',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fylke.$code.lazy').then((d) => d.Route))
const BransjeCodeRoute = BransjeCodeRouteImport.update({
  id: '/bransje/$code',
  path: '/bransje/$code',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bransje.$code.lazy').then((d) => d.Route))
const BedriftOrgnrRoute = BedriftOrgnrRouteImport.update({
  id: '/bedrift/$orgnr',
  path: '/bedrift/$orgnr',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonNameBirthdateRoute = PersonNameBirthdateRouteImport.update({
  id: '/$name/$birthdate',
  path: '/$name/$birthdate',
  getParentRoute: () => PersonRoute,
} as any).lazy(() =>
  import('./routes/person.$name.$birthdate.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/affiliates': typeof AffiliatesRoute
  '/bransjer': typeof BransjerRoute
  '/datakilder': typeof DatakilderRoute
  '/fylker': typeof FylkerRoute
  '/kart': typeof KartRoute
  '/kommuner': typeof KommunerRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/oppdateringer': typeof OppdateringerRoute
  '/person': typeof PersonRouteWithChildren
  '/personer': typeof PersonerRoute
  '/personvern': typeof PersonvernRoute
  '/regioner': typeof RegionerRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/vilkar': typeof VilkarRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/bransje/$code': typeof BransjeCodeRoute
  '/fylke/$code': typeof FylkeCodeRoute
  '/kommune/$code': typeof KommuneCodeRoute
  '/virksomhet/$orgnr': typeof VirksomhetOrgnrRoute
  '/person/': typeof PersonIndexRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/affiliates': typeof AffiliatesRoute
  '/bransjer': typeof BransjerRoute
  '/datakilder': typeof DatakilderRoute
  '/fylker': typeof FylkerRoute
  '/kart': typeof KartRoute
  '/kommuner': typeof KommunerRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/oppdateringer': typeof OppdateringerRoute
  '/personer': typeof PersonerRoute
  '/personvern': typeof PersonvernRoute
  '/regioner': typeof RegionerRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/vilkar': typeof VilkarRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/bransje/$code': typeof BransjeCodeRoute
  '/fylke/$code': typeof FylkeCodeRoute
  '/kommune/$code': typeof KommuneCodeRoute
  '/virksomhet/$orgnr': typeof VirksomhetOrgnrRoute
  '/person': typeof PersonIndexRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/affiliates': typeof AffiliatesRoute
  '/bransjer': typeof BransjerRoute
  '/datakilder': typeof DatakilderRoute
  '/fylker': typeof FylkerRoute
  '/kart': typeof KartRoute
  '/kommuner': typeof KommunerRoute
  '/konkurser': typeof KonkurserRoute
  '/nyetableringer': typeof NyetableringerRoute
  '/om': typeof OmRoute
  '/oppdateringer': typeof OppdateringerRoute
  '/person': typeof PersonRouteWithChildren
  '/personer': typeof PersonerRoute
  '/personvern': typeof PersonvernRoute
  '/regioner': typeof RegionerRoute
  '/sammenlign': typeof SammenlignRoute
  '/utforsk': typeof UtforskRoute
  '/vilkar': typeof VilkarRoute
  '/bedrift/$orgnr': typeof BedriftOrgnrRoute
  '/bransje/$code': typeof BransjeCodeRoute
  '/fylke/$code': typeof FylkeCodeRoute
  '/kommune/$code': typeof KommuneCodeRoute
  '/virksomhet/$orgnr': typeof VirksomhetOrgnrRoute
  '/person/': typeof PersonIndexRoute
  '/person/$name/$birthdate': typeof PersonNameBirthdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/affiliates'
    | '/bransjer'
    | '/datakilder'
    | '/fylker'
    | '/kart'
    | '/kommuner'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/oppdateringer'
    | '/person'
    | '/personer'
    | '/personvern'
    | '/regioner'
    | '/sammenlign'
    | '/utforsk'
    | '/vilkar'
    | '/bedrift/$orgnr'
    | '/bransje/$code'
    | '/fylke/$code'
    | '/kommune/$code'
    | '/virksomhet/$orgnr'
    | '/person/'
    | '/person/$name/$birthdate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/affiliates'
    | '/bransjer'
    | '/datakilder'
    | '/fylker'
    | '/kart'
    | '/kommuner'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/oppdateringer'
    | '/personer'
    | '/personvern'
    | '/regioner'
    | '/sammenlign'
    | '/utforsk'
    | '/vilkar'
    | '/bedrift/$orgnr'
    | '/bransje/$code'
    | '/fylke/$code'
    | '/kommune/$code'
    | '/virksomhet/$orgnr'
    | '/person'
    | '/person/$name/$birthdate'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/affiliates'
    | '/bransjer'
    | '/datakilder'
    | '/fylker'
    | '/kart'
    | '/kommuner'
    | '/konkurser'
    | '/nyetableringer'
    | '/om'
    | '/oppdateringer'
    | '/person'
    | '/personer'
    | '/personvern'
    | '/regioner'
    | '/sammenlign'
    | '/utforsk'
    | '/vilkar'
    | '/bedrift/$orgnr'
    | '/bransje/$code'
    | '/fylke/$code'
    | '/kommune/$code'
    | '/virksomhet/$orgnr'
    | '/person/'
    | '/person/$name/$birthdate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AffiliatesRoute: typeof AffiliatesRoute
  BransjerRoute: typeof BransjerRoute
  DatakilderRoute: typeof DatakilderRoute
  FylkerRoute: typeof FylkerRoute
  KartRoute: typeof KartRoute
  KommunerRoute: typeof KommunerRoute
  KonkurserRoute: typeof KonkurserRoute
  NyetableringerRoute: typeof NyetableringerRoute
  OmRoute: typeof OmRoute
  OppdateringerRoute: typeof OppdateringerRoute
  PersonRoute: typeof PersonRouteWithChildren
  PersonerRoute: typeof PersonerRoute
  PersonvernRoute: typeof PersonvernRoute
  RegionerRoute: typeof RegionerRoute
  SammenlignRoute: typeof SammenlignRoute
  UtforskRoute: typeof UtforskRoute
  VilkarRoute: typeof VilkarRoute
  BedriftOrgnrRoute: typeof BedriftOrgnrRoute
  BransjeCodeRoute: typeof BransjeCodeRoute
  FylkeCodeRoute: typeof FylkeCodeRoute
  KommuneCodeRoute: typeof KommuneCodeRoute
  VirksomhetOrgnrRoute: typeof VirksomhetOrgnrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utforsk': {
      id: '/utforsk'
      path: '/utforsk'
      fullPath: '/utforsk'
      preLoaderRoute: typeof UtforskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sammenlign': {
      id: '/sammenlign'
      path: '/sammenlign'
      fullPath: '/sammenlign'
      preLoaderRoute: typeof SammenlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioner': {
      id: '/regioner'
      path: '/regioner'
      fullPath: '/regioner'
      preLoaderRoute: typeof RegionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personer': {
      id: '/personer'
      path: '/personer'
      fullPath: '/personer'
      preLoaderRoute: typeof PersonerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person': {
      id: '/person'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof PersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppdateringer': {
      id: '/oppdateringer'
      path: '/oppdateringer'
      fullPath: '/oppdateringer'
      preLoaderRoute: typeof OppdateringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyetableringer': {
      id: '/nyetableringer'
      path: '/nyetableringer'
      fullPath: '/nyetableringer'
      preLoaderRoute: typeof NyetableringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konkurser': {
      id: '/konkurser'
      path: '/konkurser'
      fullPath: '/konkurser'
      preLoaderRoute: typeof KonkurserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommuner': {
      id: '/kommuner'
      path: '/kommuner'
      fullPath: '/kommuner'
      preLoaderRoute: typeof KommunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kart': {
      id: '/kart'
      path: '/kart'
      fullPath: '/kart'
      preLoaderRoute: typeof KartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fylker': {
      id: '/fylker'
      path: '/fylker'
      fullPath: '/fylker'
      preLoaderRoute: typeof FylkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datakilder': {
      id: '/datakilder'
      path: '/datakilder'
      fullPath: '/datakilder'
      preLoaderRoute: typeof DatakilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bransjer': {
      id: '/bransjer'
      path: '/bransjer'
      fullPath: '/bransjer'
      preLoaderRoute: typeof BransjerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/': {
      id: '/person/'
      path: '/'
      fullPath: '/person/'
      preLoaderRoute: typeof PersonIndexRouteImport
      parentRoute: typeof PersonRoute
    }
    '/virksomhet/$orgnr': {
      id: '/virksomhet/$orgnr'
      path: '/virksomhet/$orgnr'
      fullPath: '/virksomhet/$orgnr'
      preLoaderRoute: typeof VirksomhetOrgnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommune/$code': {
      id: '/kommune/$code'
      path: '/kommune/$code'
      fullPath: '/kommune/$code'
      preLoaderRoute: typeof KommuneCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fylke/$code': {
      id: '/fylke/$code'
      path: '/fylke/$code'
      fullPath: '/fylke/$code'
      preLoaderRoute: typeof FylkeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bransje/$code': {
      id: '/bransje/$code'
      path: '/bransje/$code'
      fullPath: '/bransje/$code'
      preLoaderRoute: typeof BransjeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrift/$orgnr': {
      id: '/bedrift/$orgnr'
      path: '/bedrift/$orgnr'
      fullPath: '/bedrift/$orgnr'
      preLoaderRoute: typeof BedriftOrgnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$name/$birthdate': {
      id: '/person/$name/$birthdate'
      path: '/$name/$birthdate'
      fullPath: '/person/$name/$birthdate'
      preLoaderRoute: typeof PersonNameBirthdateRouteImport
      parentRoute: typeof PersonRoute
    }
  }
}

interface PersonRouteChildren {
  PersonIndexRoute: typeof PersonIndexRoute
  PersonNameBirthdateRoute: typeof PersonNameBirthdateRoute
}

const PersonRouteChildren: PersonRouteChildren = {
  PersonIndexRoute: PersonIndexRoute,
  PersonNameBirthdateRoute: PersonNameBirthdateRoute,
}

const PersonRouteWithChildren =
  PersonRoute._addFileChildren(PersonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AffiliatesRoute: AffiliatesRoute,
  BransjerRoute: BransjerRoute,
  DatakilderRoute: DatakilderRoute,
  FylkerRoute: FylkerRoute,
  KartRoute: KartRoute,
  KommunerRoute: KommunerRoute,
  KonkurserRoute: KonkurserRoute,
  NyetableringerRoute: NyetableringerRoute,
  OmRoute: OmRoute,
  OppdateringerRoute: OppdateringerRoute,
  PersonRoute: PersonRouteWithChildren,
  PersonerRoute: PersonerRoute,
  PersonvernRoute: PersonvernRoute,
  RegionerRoute: RegionerRoute,
  SammenlignRoute: SammenlignRoute,
  UtforskRoute: UtforskRoute,
  VilkarRoute: VilkarRoute,
  BedriftOrgnrRoute: BedriftOrgnrRoute,
  BransjeCodeRoute: BransjeCodeRoute,
  FylkeCodeRoute: FylkeCodeRoute,
  KommuneCodeRoute: KommuneCodeRoute,
  VirksomhetOrgnrRoute: VirksomhetOrgnrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
