apiVersion: 1

contactPoints:
  - orgId: 1
    name: bedriftsgrafen-discord
    receivers:
      - uid: bedriftsgrafen_discord
        type: discord
        disableResolveMessage: false
        settings:
          content: '{{ template "bedriftsgrafen.discord.message" . }}'
          url: $DISCORD_WEBHOOK_URL
          use_discord_username: true